# Generated by Django 2.0.1 on 2018-07-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='image',
            field=models.ImageField(blank=True, help_text='Questionnaire image', null=True, upload_to='questionnaires/images/'),
        ),
    ]
