version: '2'
services:
  #db:
  #  image: postgres
  profsreda:
    build: .
    container_name: profsreda
    command: python3 /src/manage.py runserver 0.0.0.0:8000
    environment:
      MODE: 'dev'
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    #depends_on:
    #  - db