# Generated by Django 2.0.3 on 2018-04-23 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaire.AnswerChoice', verbose_name='Ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaire.Question')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос из анкеты',
                'verbose_name_plural': 'Ответы на вопросы из анкет',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения')),
                ('is_finished', models.BooleanField(default=False)),
                ('result', models.TextField(default='{}')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaire.Questionnaire', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прохождение теста',
                'verbose_name_plural': 'Прохождения тестов',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaire_responses.Response'),
        ),
    ]
