# Generated by Django 2.0.3 on 2018-04-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire_responses', '0002_auto_20180423_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaireresult',
            options={'verbose_name': 'Описание результата', 'verbose_name_plural': 'Описания результатов'},
        ),
        migrations.AlterModelOptions(
            name='responseresult',
            options={'verbose_name': 'Результат прохождения', 'verbose_name_plural': 'Результаты прохождений'},
        ),
        migrations.AddField(
            model_name='questionnaireresult',
            name='description3',
            field=models.TextField(blank=True, default=''),
        ),
    ]
