# Generated by Django 2.0.1 on 2018-07-24 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.TextField()),
                ('slot1', models.TextField(blank=True, default='')),
                ('slot2', models.TextField(blank=True, default='')),
                ('slot3', models.TextField(blank=True, default='')),
                ('slot4', models.TextField(blank=True, default='')),
                ('slot5', models.TextField(blank=True, default='')),
                ('slot1_girl', models.TextField(blank=True, default='')),
                ('slot2_girl', models.TextField(blank=True, default='')),
                ('slot3_girl', models.TextField(blank=True, default='')),
                ('slot4_girl', models.TextField(blank=True, default='')),
                ('slot5_girl', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='ItemUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='heroes.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Предмет у пользователя',
                'verbose_name_plural': 'Предметы у пользователей',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=400, null=True)),
                ('last_name', models.CharField(blank=True, max_length=400, null=True)),
                ('father_name', models.CharField(blank=True, max_length=400, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, null=True)),
                ('slots', models.TextField(default='[["slot1", "img/game/avatar/M/01.png"], ["slot2", "img/game/avatar/M/02.png"], ["slot3", "img/game/avatar/M/03.png"], ["slot4", "img/game/avatar/M/04.png"], ["slot5", "img/game/avatar/M/05.png"]]')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShareProfileAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(unique=True)),
                ('avatar_image', models.TextField(default='')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='itemuser',
            unique_together={('user', 'item')},
        ),
    ]
