# Generated by Django 2.0.3 on 2018-04-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='')),
                ('slot1', models.ImageField(blank=True, null=True, upload_to='')),
                ('slot2', models.ImageField(blank=True, null=True, upload_to='')),
                ('slot3', models.ImageField(blank=True, null=True, upload_to='')),
                ('slot4', models.ImageField(blank=True, null=True, upload_to='')),
                ('slot5', models.ImageField(blank=True, null=True, upload_to='')),
                ('slot1_girl', models.ImageField(blank=True, null=True, upload_to='')),
                ('slot2_girl', models.ImageField(blank=True, null=True, upload_to='')),
                ('slot3_girl', models.ImageField(blank=True, null=True, upload_to='')),
                ('slot4_girl', models.ImageField(blank=True, null=True, upload_to='')),
                ('slot5_girl', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
