# Generated by Django 2.0.1 on 2018-07-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slots',
            field=models.TextField(default='{"slot1": "img/game/avatar/M/01.png", "slot2": "img/game/avatar/M/02.png", "slot3": "img/game/avatar/M/03.png", "slot4": "img/game/avatar/M/04.png", "slot5": "img/game/avatar/M/05.png"}'),
        ),
    ]
