# Generated by Django 2.0.3 on 2018-04-24 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('heroes', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Предмет у пользователя',
                'verbose_name_plural': 'Предметы у пользователей',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='slot1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slot1_girl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slot2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slot2_girl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slot3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slot3_girl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slot4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slot4_girl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slot5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slot5_girl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemuser',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='heroes.Item'),
        ),
        migrations.AddField(
            model_name='itemuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='itemuser',
            unique_together={('user', 'item')},
        ),
    ]
