# Generated by Django 2.0.3 on 2018-04-24 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire_responses', '0003_auto_20180423_1656'),
        ('heroes', '0004_auto_20180424_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='questionnaire_responses.QuestionnaireResult'),
        ),
    ]
