# Generated by Django 2.0.3 on 2018-05-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0005_item_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slots',
            field=models.TextField(default='{"slot1": "img/game/avatar/M/01.png", "slot2": "img/game/avatar/M/02.png", "slot3": "img/game/avatar/M/03.png", "slot4": "img/game/avatar/M/04.png", "slot5": "img/game/avatar/M/05.png"}'),
        ),
    ]
