# Generated by Django 2.0.3 on 2018-05-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0006_profile_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='items',
            field=models.TextField(default='{}'),
        ),
    ]
