# Generated by Django 2.0.3 on 2018-05-02 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0007_profile_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='items',
        ),
    ]
