# Generated by Django 2.0.7 on 2018-07-23 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(help_text='Текст ответа', max_length=100, verbose_name='Ответ')),
                ('weight', models.PositiveIntegerField(help_text='Коэффициент, с которым вариант ответа учитывается при подсчёте результата', verbose_name='Коэффициент')),
            ],
            options={
                'verbose_name_plural': 'Варианты ответов',
                'verbose_name': 'Вариант ответа',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=100, verbose_name='Название')),
                ('short_description', models.TextField(help_text='Краткое описание категории', max_length=1000, verbose_name='Описание')),
                ('long_description', models.TextField(blank=True, help_text='Развёрнутое описание категории', max_length=10000, null=True, verbose_name='Развернутое описание')),
                ('item', models.ForeignKey(help_text='Награда за получение категории', on_delete=django.db.models.deletion.DO_NOTHING, to='heroes.Item', verbose_name='Награда')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Текст вопроса', max_length=100, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name_plural': 'Вопросы',
                'verbose_name': 'Вопрос',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(help_text='Время, в которое был сделан ответ', verbose_name='Время ответа')),
                ('answer', models.ForeignKey(help_text='Выбранный вариант ответа', on_delete=django.db.models.deletion.CASCADE, to='tests.Answer', verbose_name='Вариант ответа')),
            ],
            options={
                'verbose_name_plural': 'Ответы',
                'verbose_name': 'Ответ',
            },
        ),
        migrations.CreateModel(
            name='ResultCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(help_text='Категория, определённая в тесте', on_delete=django.db.models.deletion.CASCADE, to='tests.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Определённые категории',
                'verbose_name': 'Определённая категория',
            },
        ),
        migrations.CreateModel(
            name='ResultItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(help_text='Награда, полученная за прохождение теста', on_delete=django.db.models.deletion.CASCADE, to='heroes.Item', verbose_name='Награда')),
            ],
            options={
                'verbose_name_plural': 'Полученные награды',
                'verbose_name': 'Полученная награда',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название теста', max_length=100, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание теста', max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(help_text='Обложка теста', upload_to='test_images/', verbose_name='Обложка')),
            ],
            options={
                'verbose_name_plural': 'Тесты',
                'verbose_name': 'Тест',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Результаты тестов',
                'verbose_name': 'Результат теста',
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False, help_text='Значение, указывающее, закончена ли тест сессия', verbose_name='Закончена')),
                ('datetime_created', models.DateTimeField(help_text='Время, в которое пользователь начал проходить тест', verbose_name='Время старта')),
                ('datetime_finished', models.DateTimeField(blank=True, help_text='Время, в которое пользователь закончил проходить тест', null=True, verbose_name='Время завершения')),
                ('last_answered_question', models.ForeignKey(blank=True, help_text='Последний вопрос, на который ответил пользователь', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tests.Question', verbose_name='Последний отвеченный вопрос')),
                ('test', models.ForeignKey(help_text='Тест, к которому относиться сессия', on_delete=django.db.models.deletion.CASCADE, to='tests.Test', verbose_name='Тест')),
                ('user', models.ForeignKey(help_text='Пользователь, проходящий тест', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Тестируемый')),
            ],
            options={
                'verbose_name_plural': 'Тест сессии',
                'verbose_name': 'Тест сессия',
            },
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_session',
            field=models.ForeignKey(help_text='Тест сессия, которой соответствует результат', on_delete=django.db.models.deletion.DO_NOTHING, to='tests.TestSession', verbose_name='Тест сессия'),
        ),
        migrations.AddField(
            model_name='resultitem',
            name='test_result',
            field=models.ForeignKey(help_text='Результат теста, за который получена награда', on_delete=django.db.models.deletion.CASCADE, to='tests.TestResult', verbose_name='Результат теста'),
        ),
        migrations.AddField(
            model_name='resultcategory',
            name='test_result',
            field=models.ForeignKey(help_text='Результат теста, в котором определена категория', on_delete=django.db.models.deletion.CASCADE, to='tests.TestResult', verbose_name='Результат теста'),
        ),
        migrations.AddField(
            model_name='response',
            name='test_session',
            field=models.ForeignKey(help_text='Тест сессия, в которую был сделан ответ', on_delete=django.db.models.deletion.CASCADE, to='tests.TestSession', verbose_name='Тест сессия'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(help_text='Тест, к которому относится вопрос', on_delete=django.db.models.deletion.CASCADE, to='tests.Test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='category',
            name='test',
            field=models.ForeignKey(help_text='Тест, определяющий данную категорию', on_delete=django.db.models.deletion.CASCADE, to='tests.Test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='answer',
            name='category',
            field=models.ForeignKey(help_text='Категория, соответствующая варианту ответа', on_delete=django.db.models.deletion.CASCADE, to='tests.Category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(help_text='Соответствующий варианту ответа вопрос', on_delete=django.db.models.deletion.CASCADE, to='tests.Question', verbose_name='Вопрос'),
        ),
    ]
