# Generated by Django 2.0.1 on 2018-07-17 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(help_text='Обложка теста', upload_to='test_images/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='last_answered_question',
            field=models.ForeignKey(blank=True, help_text='Последний вопрос, на который ответил пользователь', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tests.Question', verbose_name='Последний отвеченный вопрос'),
        ),
    ]
