# Generated by Django 2.0.1 on 2018-07-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20180718_0209'),
        ('tests', 'renaming_models'),
    ]

    operations = [
    ]
