# Generated by Django 2.0.1 on 2018-07-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_merge_20180721_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ-Категория', 'verbose_name_plural': 'Пары Ответ-Категория'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
    ]
