# Generated by Django 2.0.1 on 2018-07-21 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20180721_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.RemoveField(
            model_name='response',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.AddField(
            model_name='response',
            name='answer',
            field=models.ForeignKey(default=2, help_text='Выбранный вариант ответа', on_delete=django.db.models.deletion.CASCADE, to='tests.Answer', verbose_name='Вариант ответа'),
            preserve_default=False,
        ),
    ]
