# Generated by Django 2.0.1 on 2018-07-21 15:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20180721_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Время, в которое пользователь начал проходить тест', verbose_name='Время старта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsession',
            name='finished',
            field=models.DateTimeField(blank=True, help_text='Время, в которое пользователь закончил проходить тест', null=True, verbose_name='Время завершения'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='category',
            field=models.ForeignKey(help_text='Категория, соответствующая варианту ответа', on_delete=django.db.models.deletion.CASCADE, to='tests.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(help_text='Соответствующий варианту ответа вопрос', on_delete=django.db.models.deletion.CASCADE, to='tests.Question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='weight',
            field=models.PositiveIntegerField(help_text='Коэффициент, с которым вариант ответа учитывается при подсчёте результата', verbose_name='Коэффициент'),
        ),
    ]
