# Generated by Django 2.0.1 on 2018-07-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20180721_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsession',
            old_name='created',
            new_name='datetime_created',
        ),
        migrations.RenameField(
            model_name='testsession',
            old_name='finished',
            new_name='datetime_finished',
        ),
    ]
