# Generated by Django 2.0.1 on 2018-07-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_auto_20180721_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='datetime_created',
            field=models.DateTimeField(help_text='Время, в которое пользователь начал проходить тест', verbose_name='Время старта'),
        ),
    ]
