# Generated by Django 2.0.1 on 2018-07-21 15:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_auto_20180721_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 15, 54, 3, 543345, tzinfo=utc), help_text='Время, в которое был сделан ответ', verbose_name='Время ответа'),
            preserve_default=False,
        ),
    ]
