# Generated by Django 2.0.1 on 2018-07-21 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_auto_20180720_0342'),
        ('tests', '0009_response_datetime_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='item',
            field=models.ForeignKey(default=2, help_text='Награда за получение категории', on_delete=django.db.models.deletion.DO_NOTHING, to='heroes.Item', verbose_name='Награда'),
            preserve_default=False,
        ),
    ]
