# Generated by Django 2.0.1 on 2018-07-21 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_category_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(help_text='Категория, определённая в тесте', on_delete=django.db.models.deletion.CASCADE, to='tests.Category', verbose_name='Категория')),
                ('test_result', models.ForeignKey(help_text='Результат теста, в котором определена категория', on_delete=django.db.models.deletion.CASCADE, to='tests.TestResult', verbose_name='Результат теста')),
            ],
            options={
                'verbose_name': 'Определённая категория',
                'verbose_name_plural': 'Определённые категории',
            },
        ),
    ]
