# Generated by Django 2.0.1 on 2018-07-21 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_auto_20180720_0342'),
        ('tests', '0011_resultcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(help_text='Награда, полученная за прохождение теста', on_delete=django.db.models.deletion.CASCADE, to='heroes.Item', verbose_name='Награда')),
                ('test_result', models.ForeignKey(help_text='Результат теста, за который получена награда', on_delete=django.db.models.deletion.CASCADE, to='tests.TestResult', verbose_name='Результат теста')),
            ],
            options={
                'verbose_name': 'Полученная награда',
                'verbose_name_plural': 'Полученные награды',
            },
        ),
    ]
