# Generated by Django 2.0.7 on 2018-07-21 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_resultitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='item',
        ),
    ]
