# Generated by Django 2.0.1 on 2018-07-22 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_remove_testresult_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='count_answered_questions',
            field=models.PositiveSmallIntegerField(default=0, help_text='Количество вопросов, на которые ответил пользователь', verbose_name='Количество отвеченных вопросов'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='next_question_to_answer',
            field=models.ForeignKey(blank=True, help_text='Следующий вопрос, на который нужно ответить', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_answer', to='tests.Question', verbose_name='Следующий вопрос'),
        ),
    ]
